<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Geode.Client.Tests</RootNamespace>
    <AssemblyName>Geode.Client.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Xunit.DependencyInjection" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Geode.Client\Geode.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Region\CachingProxy\" />
    <Folder Include="Region\CachingProxyEntryLru\" />
    <Folder Include="Region\Local\" />
    <Folder Include="Region\LocalEntryLru\" />
    <Folder Include="Region\Proxy\" />
  </ItemGroup>

</Project>
